### ISSUE TITLE
Email verification not sending

### ISSUE THREAD

**Issue by CrowMash** [gamedb/gamedb#129]
Hello,

I signed up 3 hours ago and still not receiving my verification email (even in spam inbox). Can you look into that?
It could be great if we have the ability to ask to send again that email.

For now, I have this notification if I try to log in : "Please verify your email address first"

**Comment by Jleagle** [comment]
Looking at the logs, the email was sent but blocked by your email provider based on the sender IP (SendGrid). I'll keep an eye on it and have enabled your account. Thanks.
